var express = require('express');
var Books  = require('../controller/books/books');
const router  = express.Router();
router.post("/add",Books.add);
router.post("/list",Books.list);
router.post("/update",Books.update);
router.post("/search",Books.search);
router.delete("/del/:books_id",Books.delete);
router.get("/detail/:books_id",Books.detail);
router.post("/classify",Books.classify);
module.exports =  router;
